#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    # colorscheme = "material"
    colorscheme = "dracula"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    relativenumber = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    filetree_direction = "left"
    filemanager = "nerdtree"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
# auto-completion-return-key-behavior = "complete"
# auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
  name = 'core'
  filetree_show_hidden = true
  enable_smooth_scrolling = true

[[layers]]
  name = "default"

[[layers]]
  name = "checkers"
  show_cursor_error = true
  lint_on_the_fly = true

[[layers]]
  name = 'git'

[[layers]]
  name = "treesitter"

[[layers]] 
  name = 'VersionControl'

[[layers]]
    name = "denite"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#graphql"
#
# [[layers]]
  # name = "lang#lua"

[[layers]]
  name = "gtags"

[[layers]]
  name = "lang#rust"
  format_on_save=true
  recommended_style=true

[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
  ]
  enabled_clients = ['rls']
  [layers.override_cmd]
    rust = ["rls"]


[[custom_plugins]]
    repo = "nvim-lua/plenary.nvim"
    merged = false

[[custom_plugins]]
    repo = "nvim-telescope/telescope.nvim"
    merged = false

[[custom_plugins]]
    repo = "marko-cerovac/material.nvim"
    merged = false

[[custom_plugins]]
  repo = "dracula/vim"
  name = "dracula"
  merged = false

